### ISSUE TITLE
Statis hidden until frame strata is changed

### ISSUE THREAD

**Issue by adamhl8** [DaleHuntGB/MinimapStats#2]
It seems like the minimap stats frame strata is not being applied correctly on login. The stats are hidden until I change the frame strata in options. Interestingly, a `/reload` does _not_ cause the stats to be hidden again.

**Comment by DaleHuntGB** [comment]
Appreciate the report, can you let me know if you are using any sort of Minimap AddOns alongside MinimapStats?

Also, are you on the Main Branch or the Dev Branch?

**Comment by DaleHuntGB** [comment]
I am hoping it's fixed now. If not, I will push updates post pre-patch mayhem.

**Comment by DaleHuntGB** [comment]
951d6c2 hopefully this fixes it

**Comment by Nescabir** [comment]
> Sorry, didn't see this until now. I assume this is fixed now, but if it helps I was on main branch (or whatever is on stable channel on CurseForge) and I'm using [Leatrix Plus](https://www.curseforge.com/wow/addons/leatrix-plus) which modifies the minimap frame.

I still have the same issue with Leatrix Plus (for the square mode). Even with a crazy high strata it still goes behind the frame.

**Comment by TomPerrau94** [comment]
Facing the same issue here, stats only appear after a /reload on first login.
